"""Convert the JSONL benchmark results into a TypeScript data module.

Reads:
    pmcache-20260517T031128Z-3-001/pmcache/results/baseline.jsonl
    pmcache-20260517T031128Z-3-001/pmcache/results/perceptual.jsonl
    pmcache-20260517T031128Z-3-001/pmcache/videos/qa.jsonl
    pmcache-20260517T031128Z-3-001/pmcache/smoke.json

Writes:
    demo/website/src/data/results.ts

Re-run this whenever benchmark results refresh.

Usage:
    python demo/website/scripts/build_data.py [--results-dir <path>]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_RESULTS = REPO_ROOT / "pmcache-20260517T031128Z-3-001" / "pmcache"
OUT_PATH = REPO_ROOT / "demo" / "website" / "src" / "data" / "results.ts"


def _load_jsonl(p: Path) -> list[dict]:
    return [
        json.loads(line)
        for line in p.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def _slim_row(r: dict) -> dict:
    """Keep only the fields the website needs (drop the per-frame mm_hashes
    array — we already compute its unique count)."""
    mm = r.get("mm_hashes") or []
    return {
        "video": r["video"],
        "question": r["question"],
        "gold_answer": r.get("gold_answer", ""),
        "answer": r.get("answer", ""),
        "predicted_letter": r.get("predicted_letter"),
        "mcq_answer": r.get("mcq_answer"),
        "mcq_options": r.get("mcq_options") or [],
        "num_frames": r["num_frames"],
        "unique_mm_hashes": len(set(mm)),
        "ttft_s": r["ttft_s"],
        "prompt_tokens": r.get("prompt_tokens", 0),
        "cached_tokens": r.get("cached_tokens", 0),
        "output_tokens": r.get("output_tokens", 0),
        "kv_bytes_total": r.get("kv_bytes_total", 0),
        "kv_bytes_cached": r.get("kv_bytes_cached", 0),
        "kv_bytes_recomputed": r.get("kv_bytes_recomputed", 0),
        "kv_bytes_per_token": r.get("kv_bytes_per_token", 0),
        "correct": bool(r.get("correct")),
        "variant": r["variant"],
        "tier1_hits": r.get("tier1_hits", 0),
        "tier2_hits": r.get("tier2_hits", 0),
        "tier2_rejects": r.get("tier2_rejects", 0),
        "aliased_hashes": r.get("aliased_hashes", 0),
        "pmcache_hit_rate": r.get("pmcache_hit_rate", 0.0),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", default=str(DEFAULT_RESULTS))
    parser.add_argument("--out", default=str(OUT_PATH))
    args = parser.parse_args()

    results_dir = Path(args.results_dir)
    baseline_rows = _load_jsonl(results_dir / "results" / "baseline.jsonl")
    perceptual_rows = _load_jsonl(results_dir / "results" / "perceptual.jsonl")
    qa_rows = _load_jsonl(results_dir / "videos" / "qa.jsonl")
    smoke_path = results_dir / "smoke.json"
    smoke = json.loads(smoke_path.read_text(encoding="utf-8")) if smoke_path.is_file() else {}

    baseline = [_slim_row(r) for r in baseline_rows]
    perceptual = [_slim_row(r) for r in perceptual_rows]

    # Question metadata (domain, sub_category, url) keyed by video.
    qa_meta: dict[str, dict] = {}
    for q in qa_rows:
        v = q["video"]
        meta = q.get("video_meta", {})
        qa_meta.setdefault(v, {
            "domain": meta.get("domain"),
            "sub_category": meta.get("sub_category"),
            "url": meta.get("url"),
        })

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    ts = []
    ts.append("// AUTO-GENERATED by demo/website/scripts/build_data.py")
    ts.append("// Do NOT edit by hand. Re-run the script after fresh benchmark runs.")
    ts.append("")
    ts.append('export type Variant = "baseline" | "perceptual";')
    ts.append("")
    ts.append("export interface RunRow {")
    ts.append("  video: string;")
    ts.append("  question: string;")
    ts.append("  gold_answer: string;")
    ts.append("  answer: string;")
    ts.append("  predicted_letter: string | null;")
    ts.append("  mcq_answer: string;")
    ts.append("  mcq_options: string[];")
    ts.append("  num_frames: number;")
    ts.append("  unique_mm_hashes: number;")
    ts.append("  ttft_s: number;")
    ts.append("  prompt_tokens: number;")
    ts.append("  cached_tokens: number;")
    ts.append("  output_tokens: number;")
    ts.append("  kv_bytes_total: number;")
    ts.append("  kv_bytes_cached: number;")
    ts.append("  kv_bytes_recomputed: number;")
    ts.append("  kv_bytes_per_token: number;")
    ts.append("  correct: boolean;")
    ts.append("  variant: Variant;")
    ts.append("  tier1_hits: number;")
    ts.append("  tier2_hits: number;")
    ts.append("  tier2_rejects: number;")
    ts.append("  aliased_hashes: number;")
    ts.append("  pmcache_hit_rate: number;")
    ts.append("}")
    ts.append("")
    ts.append("export interface VideoMeta {")
    ts.append("  domain?: string | null;")
    ts.append("  sub_category?: string | null;")
    ts.append("  url?: string | null;")
    ts.append("}")
    ts.append("")
    ts.append("export interface SmokeInfo {")
    ts.append("  model?: string;")
    ts.append("  smoke_elapsed_s?: number;")
    ts.append("  result?: string;")
    ts.append("}")
    ts.append("")
    ts.append(f"export const BASELINE: RunRow[] = {json.dumps(baseline, indent=2)};")
    ts.append("")
    ts.append(f"export const PERCEPTUAL: RunRow[] = {json.dumps(perceptual, indent=2)};")
    ts.append("")
    ts.append(f"export const VIDEO_META: Record<string, VideoMeta> = {json.dumps(qa_meta, indent=2)};")
    ts.append("")
    ts.append(f"export const SMOKE: SmokeInfo = {json.dumps(smoke, indent=2)};")
    ts.append("")

    out_path.write_text("\n".join(ts), encoding="utf-8")
    print(f"wrote {out_path}")
    print(f"  baseline rows:   {len(baseline)}")
    print(f"  perceptual rows: {len(perceptual)}")
    print(f"  videos:          {len(qa_meta)}")


if __name__ == "__main__":
    main()
